version: '3'
services:

    gotify:
        image: gotify/server
        expose: 
            - ${APP_PORT}
            - ${APP_PORT_SSL}
        volumes:
            - ${APP_DB_PATH}:/app/data
            - ./gotify/config.yml:/etc/gotify/config.yml
        restart: unless-stopped
        environment:
            - GOTIFY_SERVER_PORT=${APP_PORT}
            - GOTIFY_SERVER_SSL_PORT=${APP_PORT_SSL}
            - GOTIFY_DEFAULTUSER_NAME=${APP_USER_LOGIN}
            - GOTIFY_DEFAULTUSER_PASS=${APP_USER_PASSWORD}

    webserver:
        image: nginx:latest
        depends_on:
            - gotify
        container_name: gotify_nginx
        restart: unless-stopped
        environment:
            - APP_DOMAIN=${APP_DOMAIN}
            - APP_PORT=${APP_PORT}
        ports:
            - "80:80"
        volumes:
            - ./nginx/entrypoint.sh:/entrypoint.sh
            - ./nginx/default.template:/etc/nginx/conf.d/default.template
        entrypoint: ["/entrypoint.sh"]
        command: ["nginx", "-g", "daemon off;"]
