version: '3'
services:

    gotify:
        image: gotify/server
        ports:
            - '${APP_PORT}:80'
        volumes:
            - ${APP_DB_PATH}:/app/data
        environment:
            - GOTIFY_SERVER_PORT=80
            - GOTIFY_DATABASE_DIALECT=sqlite3
            - GOTIFY_DATABASE_CONNECTION=gotify.db
            - GOTIFY_DEFAULTUSER_NAME=${APP_USER_LOGIN}
            - GOTIFY_DEFAULTUSER_PASS=${APP_USER_PASSWORD}
            - GOTIFY_UPLOADEDIMAGESDIR=images
        networks:
            - gotify-network

    webserver:
        image: nginx:latest
        depends_on:
            - gotify
        container_name: gotify_nginx
        restart: unless-stopped
        environment:
            - APP_DOMAIN=${APP_DOMAIN}
            - APP_PORT=${APP_PORT}
        ports:
            - "80:80"
            - "443:443"
        networks:
            - gotify-network
        volumes:
            - ./nginx/entrypoint.sh:/entrypoint.sh
            - ./nginx/default.template:/etc/nginx/conf.d/default.template
        entrypoint: ["/entrypoint.sh"]
        command: ["nginx", "-g", "daemon off;"]

networks:
  gotify-network:
    driver: bridge